export const levels = [
    {
        id: 1,
        title: "Email Validation",
        description: "Match valid email addresses",
        testStrings: [
            { text: "user@example.com", shouldMatch: true },
            { text: "test.email@domain.org", shouldMatch: true },
            { text: "invalid.email", shouldMatch: false },
            { text: "user@", shouldMatch: false },
            { text: "another@test.co.uk", shouldMatch: true },
        ],
        hint: "Look for patterns like: characters @ characters . characters",
    },
    {
        id: 2,
        title: "Phone Numbers",
        description: "Match US phone numbers in format (XXX) XXX-XXXX",
        testStrings: [
            { text: "(555) 123-4567", shouldMatch: true },
            { text: "(999) 888-7777", shouldMatch: true },
            { text: "555-123-4567", shouldMatch: false },
            { text: "(555) 123-456", shouldMatch: false },
            { text: "(123) 456-7890", shouldMatch: true },
        ],
        hint: "Pattern: (digits) digits-digits",
    },
    {
        id: 3,
        title: "Hexadecimal Colors",
        description: "Match valid hex color codes",
        testStrings: [
            { text: "#FF5733", shouldMatch: true },
            { text: "#123ABC", shouldMatch: true },
            { text: "#GGG", shouldMatch: false },
            { text: "FF5733", shouldMatch: false },
            { text: "#abc123", shouldMatch: true },
        ],
        hint: "Hex colors start with # followed by 6 hex digits (0-9, A-F)",
    },
    {
        id: 4,
        title: "Date Format (YYYY-MM-DD)",
        description: "Match dates in ISO format",
        testStrings: [
            { text: "2025-08-04", shouldMatch: true },
            { text: "1999-12-31", shouldMatch: true },
            { text: "04-08-2025", shouldMatch: false },
            { text: "2025/08/04", shouldMatch: false },
            { text: "2025-8-4", shouldMatch: false },
        ],
        hint: "Use \\d{4}-\\d{2}-\\d{2} to match YYYY-MM-DD format",
    },
    {
        id: 5,
        title: "Slugs",
        description: "Match URL slugs (lowercase letters, numbers, hyphens only)",
        testStrings: [
            { text: "my-cool-blog-post", shouldMatch: true },
            { text: "hello-world-123", shouldMatch: true },
            { text: "not_valid_slug!", shouldMatch: false },
            { text: "UPPERCASE", shouldMatch: false },
            { text: "contains spaces", shouldMatch: false },
        ],
        hint: "Use ^[a-z0-9-]+$ to match lowercase slugs",
    },
    {
        id: 6,
        title: "Credit Card Numbers",
        description: "Match 16-digit credit card numbers grouped as 4x4 digits",
        testStrings: [
            { text: "1234 5678 9012 3456", shouldMatch: true },
            { text: "0000 1111 2222 3333", shouldMatch: true },
            { text: "1234567890123456", shouldMatch: false },
            { text: "1234-5678-9012-3456", shouldMatch: false },
            { text: "abcd efgh ijkl mnop", shouldMatch: false },
        ],
        hint: "Each group has 4 digits separated by a space",
    },
    {
        id: 7,
        title: "Floating Point Numbers",
        description: "Match positive or negative decimal numbers",
        testStrings: [
            { text: "3.14", shouldMatch: true },
            { text: "-0.001", shouldMatch: true },
            { text: "+42.0", shouldMatch: true },
            { text: "42", shouldMatch: false },
            { text: "3,14", shouldMatch: false },
        ],
        hint: "Optional sign (+/-), digits, a dot, then digits",
    },
    {
        id: 8,
        title: "HTML Tags",
        description: "Match simple HTML tags like <b>, <div>, </p>",
        testStrings: [
            { text: "<b>", shouldMatch: true },
            { text: "</div>", shouldMatch: true },
            { text: "<img>", shouldMatch: true },
            { text: "b", shouldMatch: false },
            { text: "<<p>>", shouldMatch: false },
        ],
        hint: "Use angle brackets and optional slash",
    },
    {
        id: 9,
        title: "Password Complexity",
        description: "Match passwords with at least 1 uppercase, 1 lowercase, 1 digit, 1 special character",
        testStrings: [
            { text: "P@ssw0rd", shouldMatch: true },
            { text: "Strong#123", shouldMatch: true },
            { text: "weakpassword", shouldMatch: false },
            { text: "12345678", shouldMatch: false },
            { text: "NOspecial123", shouldMatch: false },
        ],
        hint: "Look into lookaheads for multiple requirements",
    },
    {
        id: 10,
        title: "IPv4 Addresses",
        description: "Match valid IPv4 addresses like 192.168.0.1",
        testStrings: [
            { text: "192.168.0.1", shouldMatch: true },
            { text: "8.8.8.8", shouldMatch: true },
            { text: "999.999.999.999", shouldMatch: false },
            { text: "192.168.1", shouldMatch: false },
            { text: "abc.def.ghi.jkl", shouldMatch: false },
        ],
        hint: "Use \\d{1,3}(\\.\\d{1,3}){3} and later validate range if needed",
    },
]